from app.rag.indexing import QdrantIndexer


def seed_sample_documents() -> None:
    indexer = QdrantIndexer()
    documents = [
        {
            "title": "Hidden café by the lake",
            "kind": "restaurant",
            "city": "Delhi",
            "state": "Delhi",
            "budget": "low",
            "season": "winter",
            "transport": "cab",
            "family": False,
            "friends": True,
            "couples": False,
            "solo": False,
            "kids": False,
            "photography": False,
            "adventure": False,
            "nature": True,
            "food": True,
            "rating": 4.8,
            "distance": 45,
            "description": "A calm lakeside café with local biryani, chai, and peaceful seating for a slow afternoon.",
            "tags": ["food", "peaceful", "weekend", "hidden"],
        },
        {
            "title": "Quiet photography viewpoint",
            "kind": "viewpoint",
            "city": "Delhi",
            "state": "Delhi",
            "budget": "low",
            "season": "winter",
            "transport": "cab",
            "family": True,
            "friends": True,
            "couples": True,
            "solo": True,
            "kids": True,
            "photography": True,
            "adventure": False,
            "nature": True,
            "food": False,
            "rating": 4.7,
            "distance": 35,
            "description": "A scenic viewpoint with soft evening light, open skies, and low crowd density for relaxed photography.",
            "tags": ["photography", "view", "nature", "calm"],
        },
        {
            "title": "Student-friendly museum pass",
            "kind": "discount",
            "city": "Delhi",
            "state": "Delhi",
            "budget": "low",
            "season": "all",
            "transport": "metro",
            "family": False,
            "friends": True,
            "couples": False,
            "solo": True,
            "kids": False,
            "photography": False,
            "adventure": False,
            "nature": False,
            "food": False,
            "rating": 4.3,
            "distance": 20,
            "description": "A budget-friendly museum entry offer that works well for a low-cost rainy-day or indoor plan.",
            "tags": ["budget", "museum", "discount", "indoor"],
        },
    ]
    indexer.index_documents(documents)
